# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20180702_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 7, 3, 8, 31, 42, 54207, tzinfo=utc)),
        ),
    ]
