# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20180703_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 7, 3, 10, 45, 21, 395879, tzinfo=utc)),
        ),
    ]
