# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_auto_20180704_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 7, 4, 8, 55, 18, 950981, tzinfo=utc)),
        ),
    ]
