# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_auto_20180704_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 7, 4, 9, 11, 24, 546726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
