# Generated by Django 2.1.1 on 2018-09-21 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_auto_20180920_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 9, 21, 5, 46, 0, 192624, tzinfo=utc)),
        ),
    ]
