# Generated by Django 2.1.1 on 2018-09-21 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0014_auto_20180921_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 9, 21, 6, 10, 3, 46675, tzinfo=utc)),
        ),
    ]
